export default {
    GET_LIST: 'TRIPS/ GET LIST',
    SELECT: 'TRIPS/ SELECT',
    CLEAR_SELECTED_TRIP: 'TRIPS/ CLEAR SELECTED',
    ADD_TRIP: 'TRIPS/ ADD',
    UPDATE_TRIP: 'TRIPS/ UPDATE',
    DELETE_TRIP: 'TRIPS/ DELETE'
};