export default {
    GET_LIST: 'LOCATIONS/ GET LIST',
    SELECT: 'LOCATIONS/ SELECT',
    CLEAR_SELECTED_LOCATION: 'LOCATIONS/ CLEAR SELECTED',
    ADD_LOCATION: 'LOCATIONS/ ADD',
    UPDATE_LOCATION: 'LOCATIONS/ UPDATE',
    DELETE_LOCATION: 'LOCATIONS/ DELETE',
};