export default {
    GET_LIST: 'CUSTOMERS/ GET LIST',
    SELECT: 'CUSTOMERS/ SELECT',
    CLEAR_SELECTED_CUSTOMER: 'CUSTOMERS/ CLEAR SELECTED',
    ADD_CUSTOMER: 'CUSTOMERS/ ADD',
    UPDATE_CUSTOMER: 'CUSTOMERS/ UPDATE',
    DELETE_CUSTOMER: 'CUSTOMERS/ DELETE'
};